### ISSUE TITLE
payload似乎还有问题？

### ISSUE THREAD

**Issue by Mudada37** [xiaoxindada/SGSI-build-tool#38]
跑18x的包提示没有google.protobuf，但我是有的，且python3和2我都装了也不能正常运行
![截图 2022-07-31 10-16-12](https://user-images.githubusercontent.com/88835598/182006891-5f00cd86-cab2-4d67-a28b-31396a7f3f7b.png)

解压payload.bin中...
Traceback (most recent call last):
  File "./payload.py", line 7, in <module>
    import update_payload
  File "/home/mudada37/SGSI-build-tool-11/payload/update_payload/__init__.py", line 20, in <module>
    from update_payload.checker import CHECKS_TO_DISABLE
  File "/home/mudada37/SGSI-build-tool-11/payload/update_payload/checker.py", line 37, in <module>
    from update_payload import common
  File "/home/mudada37/SGSI-build-tool-11/payload/update_payload/common.py", line 21, in <module>
    from update_payload import update_metadata_pb2
  File "/home/mudada37/SGSI-build-tool-11/payload/update_payload/update_metadata_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
移动img至输出目录...
mv: 无法获取'./out/system.img' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'./out/vendor.img' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'./system.img' 的文件状态(stat): 没有那个文件或目录
mv: 无法获取'./vendor.img' 的文件状态(stat): 没有那个文件或目录
转换完成
未检测到system.img, 无法制作SGSI！

**Comment by Dangsi1** [comment]
怎么解决的
